### ISSUE TITLE
dodgy use of moodle session id

### ISSUE THREAD

**Issue by danmarsden** [WatershedLRS/moodle-report_watershed#2]
This looks really dodgy:

https://github.com/WatershedLRS/moodle-report_watershed/blob/ba3734f6e4e32dd49eafb54496a334e0fce947b8/simplesamlphp/modules/moodleauth/lib/Auth/Source/Moodle.php#L55

https://github.com/WatershedLRS/moodle-report_watershed/blob/master/checkuser.php#L37

Surely there's a better way to do this instead of passing the full Moodle session id via get?

**Comment by garemoko** [comment]
The problem I was hitting here was I wanted to use Moodle built in functions, which was proving difficult to do within the SAML library. This server side GET was a work around. 

You're right though, a better approach would be to query the database directly without having to include Moodle's built in functions. I guess I can obtain the credentials from the main Moodle config file.

**Comment by danmarsden** [comment]
My issue with this is the way it uses the cookie/session id, allowing a page that checks for full valid Moodle sessionids and passing the sessionid across in plain $_GET, - you could implement your own token inside the plugin and use that to query the db - a bit like SCORM does for AICC HACP  - just not passing the Moodle session around which could allow the full session to be compromised.

**Comment by garemoko** [comment]
Thanks @danmarsden. Let me check I've understood correctly:

1. Have the sso plugin add an additional cookie containing a unique id for the current session.
2. Add a table that maps this new unique id to the user and includes a short expiry time.  
3. Pass that new unique id in the same way that im currently passing the session id. 

Have I understood that right?

**Comment by danmarsden** [comment]
using your own cookie that doesn't expose the full Moodle session would be better, but does it need to be a cookie? - AICC code creates a time sensitive token and saves it in the db table, then passes that to the external service, the external service then passes it back when asking for the info. I haven't got a great understanding on what the plugin does/how it works as I've just done a superficial look through the code without looking at the context of any of the code.

**Comment by garemoko** [comment]
So for SSO, when the user arrives at watershed (or any system they are signing on to), there has to be something unique about that user for watershed to pass back to Moodle and say "hey, is this a valid person who's logged in?". 

I guess the AICC thing passes the token as a form or query string parameter? I guess that approach should work, but I'd have to check if that's compatible with saml and if that's more or less secure than a cookie. I have a feeling it might be less secure.

**Comment by danmarsden** [comment]
sharing cookies across multiple domains/applications sounds strange - I'm sure I've read something about that in the past but would need to do some research. All I can say definitively is that I don't think the way you are currently doing it (passing Moodle's login session in the querystring to another application) is a secure way to do it.

**Comment by garemoko** [comment]
The cookie isn't shared across domains. Following SAML, Watershed sends the user back to moodle to confirm the identity and moodle gets the cookie.

**Comment by garemoko** [comment]
Also just to be clear the current approach doesn't pass the session to another app - the get is entirely internal to moodle (but I agree it's not the best approach)

**Comment by danmarsden** [comment]
cool - obviously I didn't look too closely at the code then! :-)

**Comment by garemoko** [comment]
I discussed this with our security guy and changed it to a POST instead of a GET. The cookie id is now in the body of the request. The other thing he said was to make sure I was only exposing the user attributes that are actually needed, which is already in place. 

I considered a lot of other options here:

1. Connecting to the Moodle database directly - but this requires either including/requiring Moodle's config.php in the simplesamlphp file, which was causing errors, OR adding Moodle database credentials stuff to the simplesamlphp which I thought added too much complexity. 

2. Passing the session id as a cookie, since it already is a cookie. But given that the request is server side, this would have no benefit. 

3. Making a separate id as a proxy for the cookie id, but then if a hacker got that proxy id, it would also be a big security problem, so no win there. 

Serverside post data over HTTPS should be sufficiently secure.

**Comment by danmarsden** [comment]
POST is better - I'm still uncomfortable about the fact that it re-uses the Moodle Session id in this way but  at least there's been some consideration and discussion about it. I also assumed initially that this session id was being passed to an external service and then passed back to Moodle which doesn't seem to be the case. The other potential problem is that checkuser.php becomes a anonymous session validation script.

**Comment by garemoko** [comment]
RE "The other potential problem is that checkuser.php becomes a anonymous session validation script."

Is this also true of every page on the moodle that requires the user to be logged in?

**Comment by danmarsden** [comment]
yeah - just makes me nervous seeing it possible via a get/db request rather than using a cookie. possibly not a real issue here though.
