### ISSUE TITLE
Run Moodle coding guidelines tool 

### ISSUE THREAD

**Issue by garemoko** [WatershedLRS/moodle-report_watershed#3]
See https://moodle.org/mod/forum/discuss.php?d=323384 regarding how to set this up for travis-ci integration.

**Comment by danmarsden** [comment]
short setup: - drop .travis.yml template into root of git branch, goto https://travis-ci.org/ and setup account, add github repos that you want to monitor. Done.

**Comment by garemoko** [comment]
This is now set up, though I suspect the bigger job will be to get it passing!

**Comment by garemoko** [comment]
TODO:
- [ ] Ignore the simplesaml directory EXCEPT the modules/moodleauth folder. https://github.com/moodlerooms/moodle-plugin-ci/blob/master/doc/IgnoringFiles.md

- [ ] Fix all the issues!

**Comment by danmarsden** [comment]
you don't have to make it pass everything to get it through the plugins review process but it helps with getting other people to approve your plugin for installation if it passes the standard stuff.

**Comment by danmarsden** [comment]
I would also suggest using the thirdpartylibs.php method - as that will get picked up during the plugins review process too.

**Comment by garemoko** [comment]
thirdpartylibs.xml added - is that what you meant?

**Comment by garemoko** [comment]
Todo - find out why "The use of function error_log() is forbidden"

**Comment by garemoko** [comment]
https://github.com/moodlerooms/moodle-plugin-ci/issues/23

**Comment by garemoko** [comment]
Aside from "The use of function error_log() is forbidden" all issues have been resolved.

**Comment by danmarsden** [comment]
haha - cool, there are a few things I find annoying about the coding guidelines sometimes too... :-)

**Comment by danmarsden** [comment]
yeah - thirdpartylibs.php is usually better than defining some files to be excluded from the tests - typically the reason you don't want them to run through the tests is because they are externally sourced files anyway and should be listed in the thirdpartylibs.php file.
